[tool.black]
target-version = ['py311']
line_length = 79
preview = 1

[tool.isort]
line_length = 79
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
combine_as_imports = true

[tool.ruff]
target-version = "py311"
line-length = 99
